src/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using pieshop.Models;

namespace pieshop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Controllers/PieController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using pieshop.Models;

namespace pieshop.Controllers
{
	public class PieController : Controller
	{
			private readonly IPieRepository _pieRepository;
			private readonly ICategoryRepository _categoryRepository;

			public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
			{
				_pieRepository = pieRepository;
				_categoryRepository = categoryRepository;
			}

			public ViewResult List(string category)
			{
				IEnumerable<Pie> pies;
				string currentCategory;

				if(string.IsNullOrEmpty(category))
				{
					pies = _pieRepository.AllPies.OrderBy(p => p.PieId);
					currentCategory = "All Pies";
				}
				else
				{
					pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category)
						.OrderBy(p => p.PieId);
					currentCategory = category;
				}

				return View(
					new PieListViewModel
					{
						Pies = pies,
						CurrentCategory = currentCategory
					}
				);
			}

			public IActionResult Details(int id)
			{
				var pie = _pieRepository.GetPieById(id);

				if(pie == null)				
					return NotFound();	
			
				return View(pie);
			}
    }
}

src/Controllers/ShoppingCartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using pieshop.Models;

namespace src.Controllers
{
	public class ShoppingCartController : Controller
	{
		private readonly IPieRepository _pieRepository;
		private readonly ShoppingCart _shoppingCart;

		public ShoppingCartController(IPieRepository pieRepository, ShoppingCart shoppingCart)
		{
			_pieRepository = pieRepository;
			_shoppingCart = shoppingCart;
		}

		public IActionResult Index()
		{
			var items = _shoppingCart.GetShoppingCartItems();
			_shoppingCart.ShoppingCartItems = items;

			var shoppingCartViewModel = new ShoppingCartViewModel
			{
				ShoppingCart = _shoppingCart,
				ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
			};

			return View(shoppingCartViewModel);
		}

		public RedirectToActionResult AddToShoppingCart(int pieId)
		{
			var selectedPie = _pieRepository.AllPies.FirstOrDefault(p => p.PieId == pieId);

			if (selectedPie != null)
			{
				_shoppingCart.AddToCart(selectedPie, 1);
			}

			return RedirectToAction("Index");
		}

		public RedirectToActionResult RemoveFromShoppingCart(int pieId)
		{
			var selectedPie = _pieRepository.AllPies.FirstOrDefault(p => p.PieId == pieId);

			if (selectedPie != null)
			{
				_shoppingCart.RemoveFromCart(selectedPie);
			}

			return RedirectToAction("Index");
		}
	}
}

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<title>Odd Pie Shop</title>

		<environment include="Development">
			@RenderSection("Style", required: true)
		</environment>
		
		<link rel="icon" type="image/svg+xml" href="~/images/favicon.svg">

		<script src="https://kit.fontawesome.com/df3d0cc377.js"
			crossorigin="anonymous"></script>
	</head>
	<body>
		<header>
			<a asp-controller="Home" asp-action="Index" class="logo"
			id="logo-container">
				<img src="~/images/logo.svg"
					id="logo"
					alt="Odd Pie Shop logo" />
			</a><!-- End of logo -->
			
			<ul id="nav" class="header-menu" role="navigation">
				<li class="nav__item">
					<a asp-controller="Home" asp-action="Index">
						Home
					</a>
				</li>

				@await Component.InvokeAsync("CategoryMenu")

				<li class="nav__item">
					<a asp-controller="Contact" asp-action="Index">
						Contact
					</a>
				</li>		

				@await Component.InvokeAsync("ShoppingCartSummary")				
			</ul>

			<partial name="_LoginPartial" />
		</header>	

		<main>
			@RenderBody()
		</main>
		@RenderSection("Scripts", required: false)
	</body>
</html>

src/Views/Shared/_PieCard.cshtml
@model Pie

<div class="pie">
	<img src=@Model.ImageUrl
		class="pie-image"
		alt="@Model.Name image" />
	<h2>
		<a class="pie-name"
			asp-controller="Pie"
			asp-action="Details"	
			asp-route-id="@Model.PieId">
			@Model.Name
		</a>
	</h2>
	<h2 class="price">@Model.Price.ToString("c")</h2>
	<h2>@Model.Category.CategoryName</h2>
	<p>@Model.ShortDescription</p>
	<a class="addToCartBtn"
		asp-controller="ShoppingCart"
		asp-action="AddToShoppingCart"
		asp-route-pieId="@Model.PieId">
		Add to cart
	</a>
</div>